import {
  Hospital,
  Doctor,
  Patient,
  Appointment,
  RevenueData,
  DashboardStats,
  DemographicData,
  ConditionData,
} from "@/types";

export const hospital: Hospital = {
  id: "h1",
  name: "Shree Sai Multi-Specialty Hospital",
  address: "MG Road, Pune, Maharashtra 411001",
  phone: "+91 20 2612 3456",
  email: "admin@shreesaihospital.in",
  adminName: "Dr. Rajesh Kulkarni",
  createdAt: "2023-01-15",
};

export const doctors: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Ananya Sharma",
    specialty: "Cardiology",
    phone: "+91 98765 43210",
    email: "ananya.sharma@shreesai.in",
    hospitalId: "h1",
    patientsCount: 142,
    rating: 4.8,
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    appointmentsToday: 8,
    status: "active",
    joinedAt: "2023-03-01",
  },
  {
    id: "d2",
    name: "Dr. Vikram Patel",
    specialty: "Orthopedics",
    phone: "+91 98765 43211",
    email: "vikram.patel@shreesai.in",
    hospitalId: "h1",
    patientsCount: 98,
    rating: 4.6,
    availableDays: ["Mon", "Wed", "Fri"],
    appointmentsToday: 6,
    status: "active",
    joinedAt: "2023-04-15",
  },
  {
    id: "d3",
    name: "Dr. Priya Deshmukh",
    specialty: "Dermatology",
    phone: "+91 98765 43212",
    email: "priya.deshmukh@shreesai.in",
    hospitalId: "h1",
    patientsCount: 210,
    rating: 4.9,
    availableDays: ["Mon", "Tue", "Thu", "Sat"],
    appointmentsToday: 12,
    status: "active",
    joinedAt: "2023-02-10",
  },
  {
    id: "d4",
    name: "Dr. Arjun Mehta",
    specialty: "General Medicine",
    phone: "+91 98765 43213",
    email: "arjun.mehta@shreesai.in",
    hospitalId: "h1",
    patientsCount: 320,
    rating: 4.5,
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    appointmentsToday: 15,
    status: "active",
    joinedAt: "2023-01-20",
  },
  {
    id: "d5",
    name: "Dr. Sneha Iyer",
    specialty: "Pediatrics",
    phone: "+91 98765 43214",
    email: "sneha.iyer@shreesai.in",
    hospitalId: "h1",
    patientsCount: 175,
    rating: 4.7,
    availableDays: ["Mon", "Tue", "Wed", "Fri"],
    appointmentsToday: 10,
    status: "active",
    joinedAt: "2023-05-01",
  },
  {
    id: "d6",
    name: "Dr. Rohan Joshi",
    specialty: "ENT",
    phone: "+91 98765 43215",
    email: "rohan.joshi@shreesai.in",
    hospitalId: "h1",
    patientsCount: 88,
    rating: 4.4,
    availableDays: ["Tue", "Thu", "Sat"],
    appointmentsToday: 5,
    status: "active",
    joinedAt: "2023-06-15",
  },
  {
    id: "d7",
    name: "Dr. Kavita Nair",
    specialty: "Gynecology",
    phone: "+91 98765 43216",
    email: "kavita.nair@shreesai.in",
    hospitalId: "h1",
    patientsCount: 156,
    rating: 4.8,
    availableDays: ["Mon", "Wed", "Fri"],
    appointmentsToday: 0,
    status: "on-leave",
    joinedAt: "2023-03-20",
  },
  {
    id: "d8",
    name: "Dr. Sanjay Gupta",
    specialty: "Neurology",
    phone: "+91 98765 43217",
    email: "sanjay.gupta@shreesai.in",
    hospitalId: "h1",
    patientsCount: 67,
    rating: 4.9,
    availableDays: ["Mon", "Tue", "Thu"],
    appointmentsToday: 4,
    status: "active",
    joinedAt: "2023-07-01",
  },
];

export const patients: Patient[] = [
  {
    id: "p1",
    name: "Ramesh Kumar",
    age: 55,
    gender: "male",
    phone: "+91 99876 54321",
    doctorId: "d1",
    doctorName: "Dr. Ananya Sharma",
    condition: "Hypertension",
    medicines: ["Amlodipine 5mg", "Telmisartan 40mg"],
    lastVisit: "2026-03-18",
    nextVisit: "2026-04-18",
    adherencePercent: 92,
    status: "active",
    createdAt: "2024-01-10",
  },
  {
    id: "p2",
    name: "Sunita Devi",
    age: 42,
    gender: "female",
    phone: "+91 99876 54322",
    doctorId: "d4",
    doctorName: "Dr. Arjun Mehta",
    condition: "Type 2 Diabetes",
    medicines: ["Metformin 500mg", "Glimepiride 1mg"],
    lastVisit: "2026-03-20",
    nextVisit: "2026-04-20",
    adherencePercent: 78,
    status: "active",
    createdAt: "2024-02-15",
  },
  {
    id: "p3",
    name: "Anil Patil",
    age: 63,
    gender: "male",
    phone: "+91 99876 54323",
    doctorId: "d1",
    doctorName: "Dr. Ananya Sharma",
    condition: "Coronary Artery Disease",
    medicines: ["Aspirin 75mg", "Atorvastatin 20mg", "Metoprolol 50mg"],
    lastVisit: "2026-03-15",
    nextVisit: "2026-03-29",
    adherencePercent: 85,
    status: "critical",
    createdAt: "2023-11-20",
  },
  {
    id: "p4",
    name: "Meena Kulkarni",
    age: 35,
    gender: "female",
    phone: "+91 99876 54324",
    doctorId: "d3",
    doctorName: "Dr. Priya Deshmukh",
    condition: "Psoriasis",
    medicines: ["Betamethasone cream", "Methotrexate 7.5mg"],
    lastVisit: "2026-03-19",
    nextVisit: "2026-04-19",
    adherencePercent: 95,
    status: "active",
    createdAt: "2024-05-10",
  },
  {
    id: "p5",
    name: "Suresh Jadhav",
    age: 48,
    gender: "male",
    phone: "+91 99876 54325",
    doctorId: "d2",
    doctorName: "Dr. Vikram Patel",
    condition: "Lumbar Spondylosis",
    medicines: ["Diclofenac 50mg", "Pregabalin 75mg"],
    lastVisit: "2026-03-17",
    nextVisit: "2026-04-01",
    adherencePercent: 70,
    status: "active",
    createdAt: "2024-03-22",
  },
  {
    id: "p6",
    name: "Priya Nair",
    age: 28,
    gender: "female",
    phone: "+91 99876 54326",
    doctorId: "d5",
    doctorName: "Dr. Sneha Iyer",
    condition: "Asthma",
    medicines: ["Budesonide inhaler", "Montelukast 10mg"],
    lastVisit: "2026-03-14",
    nextVisit: "2026-04-14",
    adherencePercent: 88,
    status: "active",
    createdAt: "2024-06-01",
  },
  {
    id: "p7",
    name: "Govind Rao",
    age: 70,
    gender: "male",
    phone: "+91 99876 54327",
    doctorId: "d8",
    doctorName: "Dr. Sanjay Gupta",
    condition: "Parkinson's Disease",
    medicines: ["Levodopa 250mg", "Carbidopa 25mg"],
    lastVisit: "2026-03-10",
    nextVisit: "2026-03-24",
    adherencePercent: 65,
    status: "critical",
    createdAt: "2023-09-15",
  },
  {
    id: "p8",
    name: "Lakshmi Menon",
    age: 50,
    gender: "female",
    phone: "+91 99876 54328",
    doctorId: "d4",
    doctorName: "Dr. Arjun Mehta",
    condition: "Hypothyroidism",
    medicines: ["Levothyroxine 50mcg"],
    lastVisit: "2026-03-20",
    nextVisit: "2026-06-20",
    adherencePercent: 97,
    status: "active",
    createdAt: "2024-01-05",
  },
  {
    id: "p9",
    name: "Deepak Chavan",
    age: 38,
    gender: "male",
    phone: "+91 99876 54329",
    doctorId: "d6",
    doctorName: "Dr. Rohan Joshi",
    condition: "Chronic Sinusitis",
    medicines: ["Amoxicillin 500mg", "Fluticasone nasal spray"],
    lastVisit: "2026-03-12",
    adherencePercent: 82,
    status: "recovered",
    createdAt: "2024-07-20",
  },
  {
    id: "p10",
    name: "Asha Bhosale",
    age: 60,
    gender: "female",
    phone: "+91 99876 54330",
    doctorId: "d1",
    doctorName: "Dr. Ananya Sharma",
    condition: "Atrial Fibrillation",
    medicines: ["Warfarin 5mg", "Digoxin 0.25mg"],
    lastVisit: "2026-03-21",
    nextVisit: "2026-04-04",
    adherencePercent: 90,
    status: "active",
    createdAt: "2023-12-01",
  },
  {
    id: "p11",
    name: "Manoj Shirke",
    age: 45,
    gender: "male",
    phone: "+91 99876 54331",
    doctorId: "d4",
    doctorName: "Dr. Arjun Mehta",
    condition: "GERD",
    medicines: ["Pantoprazole 40mg", "Domperidone 10mg"],
    lastVisit: "2026-03-16",
    nextVisit: "2026-04-16",
    adherencePercent: 75,
    status: "active",
    createdAt: "2024-04-10",
  },
  {
    id: "p12",
    name: "Rekha Sawant",
    age: 32,
    gender: "female",
    phone: "+91 99876 54332",
    doctorId: "d7",
    doctorName: "Dr. Kavita Nair",
    condition: "PCOS",
    medicines: ["Metformin 500mg", "OC Pills"],
    lastVisit: "2026-03-08",
    nextVisit: "2026-04-08",
    adherencePercent: 80,
    status: "active",
    createdAt: "2024-08-15",
  },
];

export const todayAppointments: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    patientName: "Ramesh Kumar",
    doctorId: "d1",
    doctorName: "Dr. Ananya Sharma",
    date: "2026-03-21",
    time: "09:00",
    type: "follow-up",
    status: "completed",
  },
  {
    id: "a2",
    patientId: "p2",
    patientName: "Sunita Devi",
    doctorId: "d4",
    doctorName: "Dr. Arjun Mehta",
    date: "2026-03-21",
    time: "09:30",
    type: "scheduled",
    status: "completed",
  },
  {
    id: "a3",
    patientId: "p10",
    patientName: "Asha Bhosale",
    doctorId: "d1",
    doctorName: "Dr. Ananya Sharma",
    date: "2026-03-21",
    time: "10:00",
    type: "scheduled",
    status: "in-progress",
  },
  {
    id: "a4",
    patientId: "p5",
    patientName: "Suresh Jadhav",
    doctorId: "d2",
    doctorName: "Dr. Vikram Patel",
    date: "2026-03-21",
    time: "10:30",
    type: "follow-up",
    status: "waiting",
  },
  {
    id: "a5",
    patientId: "p4",
    patientName: "Meena Kulkarni",
    doctorId: "d3",
    doctorName: "Dr. Priya Deshmukh",
    date: "2026-03-21",
    time: "11:00",
    type: "scheduled",
    status: "waiting",
  },
  {
    id: "a6",
    patientId: "p8",
    patientName: "Lakshmi Menon",
    doctorId: "d4",
    doctorName: "Dr. Arjun Mehta",
    date: "2026-03-21",
    time: "11:30",
    type: "walk-in",
    status: "waiting",
  },
  {
    id: "a7",
    patientId: "p3",
    patientName: "Anil Patil",
    doctorId: "d1",
    doctorName: "Dr. Ananya Sharma",
    date: "2026-03-21",
    time: "14:00",
    type: "emergency",
    status: "waiting",
  },
  {
    id: "a8",
    patientId: "p7",
    patientName: "Govind Rao",
    doctorId: "d8",
    doctorName: "Dr. Sanjay Gupta",
    date: "2026-03-21",
    time: "14:30",
    type: "scheduled",
    status: "waiting",
  },
  {
    id: "a9",
    patientId: "p11",
    patientName: "Manoj Shirke",
    doctorId: "d4",
    doctorName: "Dr. Arjun Mehta",
    date: "2026-03-21",
    time: "15:00",
    type: "follow-up",
    status: "waiting",
  },
  {
    id: "a10",
    patientId: "p6",
    patientName: "Priya Nair",
    doctorId: "d5",
    doctorName: "Dr. Sneha Iyer",
    date: "2026-03-21",
    time: "15:30",
    type: "scheduled",
    status: "waiting",
  },
];

export const dashboardStats: DashboardStats = {
  totalPatients: 1256,
  activeDoctors: 7,
  todayAppointments: 10,
  monthlyRevenue: 1847500,
  revenueChange: 12.5,
  patientChange: 8.3,
};

export const revenueData: RevenueData[] = [
  { month: "Oct", revenue: 1520000, patients: 380 },
  { month: "Nov", revenue: 1680000, patients: 420 },
  { month: "Dec", revenue: 1450000, patients: 362 },
  { month: "Jan", revenue: 1720000, patients: 430 },
  { month: "Feb", revenue: 1650000, patients: 412 },
  { month: "Mar", revenue: 1847500, patients: 462 },
];

export const demographics: DemographicData[] = [
  { ageGroup: "0-18", count: 188, percentage: 15 },
  { ageGroup: "19-30", count: 251, percentage: 20 },
  { ageGroup: "31-45", count: 339, percentage: 27 },
  { ageGroup: "46-60", count: 289, percentage: 23 },
  { ageGroup: "60+", count: 189, percentage: 15 },
];

export const topConditions: ConditionData[] = [
  { condition: "Type 2 Diabetes", count: 198, percentage: 15.8 },
  { condition: "Hypertension", count: 176, percentage: 14.0 },
  { condition: "Asthma / COPD", count: 124, percentage: 9.9 },
  { condition: "Thyroid Disorders", count: 112, percentage: 8.9 },
  { condition: "Arthritis", count: 98, percentage: 7.8 },
  { condition: "GERD", count: 87, percentage: 6.9 },
  { condition: "Skin Conditions", count: 82, percentage: 6.5 },
  { condition: "Heart Disease", count: 76, percentage: 6.1 },
];

export const adherenceData = [
  { range: "90-100%", count: 402, percentage: 32 },
  { range: "75-89%", count: 377, percentage: 30 },
  { range: "50-74%", count: 302, percentage: 24 },
  { range: "Below 50%", count: 175, percentage: 14 },
];
